### ISSUE TITLE
bull-board in pm2 cluster mode

### ISSUE THREAD

**Issue by SqueezedLight** [vcapretz/bull-board#108]
Hi guys,
it seems `bull-board` doesn't work in pm2 cluster mode. This issue is not the same as #33 or #48 i think - these two issues kind of mix up redis cluster mode and pm2/node cluster mode. But in our case i mean pm2 cluster (just for clarification).

Here is the problem: `bull-board` works just fine. But in production a http request is handled from one out of 8 processes due to the cluster mode. All bull queues are registered in the master process. So if the request to `GET /admin/queues/queues/?` is handled by the master process the queues and jobs show up. If the http request is handled by any of the other 7 node processes the queues don't show up. This means `bull-board` shows "No stats to display" most of the time.

Is there a way to fix this? If yes i'm happy to contribute with a little hint, what to change ;)

Thanks and best regards

**Comment by Heartz66** [comment]
In your case I would recommend to simply forward the bull-board endpoint to your master worker instead of balancing them between all your workers, or you need to register the bull queues to bull-board on all your workers.

**Comment by SqueezedLight** [comment]
Thanks @Heartz66 for your quick reply. I decided to register the queues on all workers. One thing to note is, that in this case one has to make sure that the jobs in the queue are still completed one after one and not in parallel. If jobs are not completed one after one any more, it is most likely due to the fact, that the process function is triggered from every worker. You can fix this with the following:

```js
const os = require('os');

if (process.env && process.env.pm_id) {
    if (process.env.pm_id % os.cpus().length === 0) {
        const processorPath = path.join(__dirname, 'processors', 'job.js');
        this.queue.process(1, processorPath);
    }
}
```

This registers the process function only on the node master process. Thanks for the support!
