### ISSUE TITLE
Ability to set custom headers on Http Requests

### ISSUE THREAD

**Issue by TobiGe** [vcapretz/bull-board#109]
Hi everyone, 

I am currently trying to integrate bull-board into an admin-dashboard using react-admin. 
We are using Nest.js as the backend framework and have successfully integrated bull-board into our Nest.js App using the technique outlined in Issue #95  
When accessing it without any authentication, everything works as expected and bull-board can be accessed (even embedded in an iFrame) and displays our queues. 

Now to support our authentication scheme, we placed several middlewares (that validate tokens, roles..) in front of the "UI" function that is imported from bull-board when mounting. 
Naturally, the http-requests made by bull-board do not carry the necessary http-headers to pass through that middleware. 

Thus, my question would be: Is it in any way possible to customize the http-headers carried by bull-board's requests? 

Thanks in advance.

**Comment by vcapretz** [comment]
Hey @TobiGe, I don't think it's really possible atm 😕

I just never really considered/worked on that case scenario, but if you have time to send a PR I would gladly review and publish it! 

(if you want to make it available in the current latest version instead of the alpha, branch off from the `latest-stable` branch please 😄)

**Comment by TobiGe** [comment]
Hi @vcapretz, 

we settled on using a different authentication scheme for the sole purpose of authenticating requests to the route that serves the bull-board. When there are resources available to improve the experience for our admin-panel, we will re-visit the the possibility of adding custom headers to bull-boards requests. For now, we are okay with what could be achieved without it. 

Thanks for the clarification! :)
