### ISSUE TITLE
Can't see the result of JOB

### ISSUE THREAD

**Issue by alanhong902** [vcapretz/bull-board#126]
Job process returns a string as result of job once it's completed, but there's no view for checking the result of bull-board's dashboard. Does anyone know the way to see the result?

**Comment by kyleolsondesign** [comment]
Fixed in https://github.com/vcapretz/bull-board/pull/190, I believe. But not yet released :)

I was looking for the exact same thing :)

**Comment by felixmosh** [comment]
Sorry, I've missed the fact that we didn't released it.
A release [PR](#200) was made :]
