### ISSUE TITLE
Helmet 4.x with Bull board breaks the dashboard.

### ISSUE THREAD

**Issue by srshkmr** [vcapretz/bull-board#130]
Getting the following error with helmet 4.x with bull-board 0.9.0

Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

**Comment by throrin19** [comment]
same problem here with helmet 4.2.0 and bull-board 0.9.0

**Comment by felixmosh** [comment]
> same problem here with helmet 4.2.0 and bull-board 0.9.0

Latest master has a fix for it.
