### ISSUE TITLE
Is there a way to overwrite the basePath?

### ISSUE THREAD

**Issue by eduardrock** [vcapretz/bull-board#131]
My bull-board path is defined inside a custom basePath, but when I load the dashboard it fails because it removes my custom basePath

**Comment by eduardrock** [comment]
@vcapretz

**Comment by pcandido** [comment]
The same here.
It cannot find static/bundle.js on the right path. It returns 404.

**Comment by pcandido** [comment]
I got it.

Actually, proxyUrl is exactly for customization. You could set it into your req, as suggested here:

https://github.com/vcapretz/bull-board/blob/master/CHANGELOG.md#added-2

So, I did it:
```
const { UI } = require('bull-board')

app.use('/admin/queues', (req, res, next) => {
    req.proxyUrl = /context/admin/queues';
    next();
}, UI)
```
