### ISSUE TITLE
Issue with Display

### ISSUE THREAD

**Issue by dc-deal** [vcapretz/bull-board#156]
hello, thanks for hearing me out.

Bull-Board UI is working. But the display presentation - seems to be wrong. Appears to be some CSS missing eventually? 
I'm Running Node.js on a Windows machine

I Hope i didn't miss some important stuff you wrote on the Readme, i went trough it several times.

The Way i see it - not like the way it looks like the pictures in your Readme.

![2020-11-10 08_58_35-Window](https://user-images.githubusercontent.com/11649712/98784815-f8087780-23fb-11eb-892d-1ebc7f7752ca.png)

**Comment by felixmosh** [comment]
This was the old design, it changed in the v1.10-alpha, you can install it from `npm` using 
```shell
npm install bull-board@1.0.0-alpha.12
```
Or using `git clone` from master

**Comment by dc-deal** [comment]
Thanks a lot!
