### ISSUE TITLE
Design bug: jobId overlap job name

### ISSUE THREAD

**Issue by paeolo** [vcapretz/bull-board#159]
I noticed a bug in the design (CSS I guess) of the bull-board ui. When the jobId is too long, it will overlap with the job name.

![bulllboard_overlap](https://user-images.githubusercontent.com/32302162/100073805-3eb79200-2e3e-11eb-8e45-d4bbf79c3dc8.png)

I suggest to use an ellipsis for the jobId for instance, since you can still view it clicking on the "options" tab. Or maybe changing the vertical alignement.
Cheers,
Paul

**Comment by felixmosh** [comment]
Thanx for reporting this issue 🙏🏼

I will check it asap

**Comment by paeolo** [comment]
BTW I just took a look at your UI code. It's a pleasure to see a well written react app;)
