### ISSUE TITLE
Design bug: data outside of div

### ISSUE THREAD

**Issue by lukepolo** [vcapretz/bull-board#161]
Long data will go outside of the container.
![image](https://user-images.githubusercontent.com/2066668/100115898-141b0880-2e41-11eb-980a-7e8d3be0614b.png)

![image](https://user-images.githubusercontent.com/2066668/100115931-2137f780-2e41-11eb-9543-ffced7841bb4.png)

**Comment by felixmosh** [comment]
Thank you for reporting this issue, 🙏🏼
I will check it out asap.

BTW, PRs are always wellcome 
BTW 2, how did you changed the position of the menu to right? 😎

**Comment by lukepolo** [comment]
Sorry just saw this reply. I have two instances of it open . 

We have a very complex system and requires me to have two version of redis / queues operating!
