### ISSUE TITLE
bullmq required module but using bull

### ISSUE THREAD

**Issue by Heartz66** [vcapretz/bull-board#167]
I am using `bull`, not `bullmq`, and when I try to compile using typescript I receive the following compiler error:

`error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.`

Meanwhile, the issue is resolved aftering install `bullmq`

**Comment by felixmosh** [comment]
What is the file that requires it?

**Comment by FPNL** [comment]
> What is the file that requires it?

seems dist/index.js:8 need it,
I tried to move bullmq to dependencies from devDependencies in `package.json`, then it installed.

**Comment by k2s** [comment]
`bullmq` it is required in `dist/index.js`. In fact it is never loading `bull` package.
Do we need to compile own package if we want to use `bull` ?
Could `bull-board` except `bull` library to use on initialization ?

**Comment by felixmosh** [comment]
You are right, `bullmq` is used here https://github.com/vcapretz/bull-board/blob/master/src/index.ts#L43, therefore, it should be a `dependency` instead of dev dependency.

Regarding this, 
> Could bull-board except bull library to use on initialization ?
I'm not sure i understood your meaning.

**Comment by k2s** [comment]
@felixmosh my quick idea to make bull-board independent from bull version was something like:

```
const Bull = require('???')

const { router, setQueues } = require('bull-board')
setQueues([q1, q2], Bull)
```
`bull-board` would not need to have bull library as dependency or only one as fallback if not provided by user.

**Comment by felixmosh** [comment]
@k2s , Ha got the idea, but there are 2 concerns with it:
1. `bull-board` using lib's typescript interfaces
2. If you pass the instances from out-side, it may break, since `bull-board` is invoking methods on those instances => api may change => `bull-board` won't work.

I think that it is better to remove the only [usage](https://github.com/vcapretz/bull-board/blob/master/src/index.ts#L43), and make it a read devDeps.

@vcapretz WDYT?

**Comment by vcapretz** [comment]
I agree on removing the usage, it seems like it can be solved in other ways, I am just not sure what properties we can look at to decide if it's a queue from bull or bullmq 🤔

**Comment by k2s** [comment]
@vcapretz if you need to know which bull library is in use, then what about changing my proposal to use second parameter into options.

```
setQueues([q1, q2], {bull: require('bull')}l)
// or
setQueues([q1, q2], {bullmq: require('bullmq')}l)
```

**Comment by felixmosh** [comment]
> @vcapretz if you need to know which bull library is in use, then what about changing my proposal to use second parameter into options.
> 
> ```
> setQueues([q1, q2], {bull: require('bull')}l)
> // or
> setQueues([q1, q2], {bullmq: require('bullmq')}l)
> ```

Thank you for the suggestion, I found more checks like this (https://github.com/vcapretz/bull-board/blob/a0de3877e720230a0dd08a2b262f822a52bb018a/src/routes/cleanAll.ts#L28), we need to refactor the code so it will be agnostic to the lib type.
I've opened an issue for it, https://github.com/vcapretz/bull-board/issues/174
