### ISSUE TITLE
v1 release exports router instead of UI

### ISSUE THREAD

**Issue by k2s** [vcapretz/bull-board#168]
Examples for v1 tag show `const { UI } = require('bull-board')`, but `UI` is never exported from `bull-board/dist/index.js`, it exports `router`, which works.

**Comment by felixmosh** [comment]
It is a major release, we decided to change the interface a bit.

Instead of invoking `UI` function, you get the `router` which is what `UI` was returning, check the usage in [example.js](https://github.com/vcapretz/bull-board/blob/master/example.js)

**Comment by vcapretz** [comment]
PR up for updating the readme file! thanks for the catch @k2s 👍
