### ISSUE TITLE
View returnValue for completed jobs?

### ISSUE THREAD

**Issue by grahamb** [vcapretz/bull-board#184]
bull-board doesn't seem to display the data passed to the done callback for completed jobs (the `returnValue`). For example, in a worker:

```
done(null, {foo: 'bar'})
```

It would be very useful to be able to see this data. Am I missing something or it not available in bull-board?

**Comment by romain130492** [comment]
any news about this? the job doesnt show up in `completed` when passing 2 parameter into `done`
ex: `done(null,{})`

Using bull with 
```
  jobQueue.add(
      { videoId, clipsToDownload },
      {
        removeOnComplete: false,
        removeOnFail: false,
      },
    );
```

thx!
