### ISSUE TITLE
How do I use basePath?

### ISSUE THREAD

**Issue by softbrix** [vcapretz/bull-board#217]
I would like to host the bull-board as an admin addon to one of my image services.

I works fine when I'm on localhost ie. http://localhost:3000/queuestatus.
But on my server the app is hosted under a sub path: https://<server_name>/<application_name>/queuestatus. 
I've seen a basePath variable in the code but no documentation on how to configure it.
Now the bull-board app fails to load the css and js files from the server because it tries to load them from https://<server_name>/queuestatus/<resources>...

I would like to see some documentation/example on how to use the basePath variable.

Thanks in advance.
/Andreas

**Comment by felixmosh** [comment]
https://github.com/vcapretz/bull-board/issues/131#issuecomment-685081738
Is it helps?

**Comment by softbrix** [comment]
Works great with a little tweak:
`const { router } = require('bull-board')

// ... express server code and a definition of basePath

app.use('/admin/queuestat', (req, res, next) => {
    req.proxyUrl = basePath + 'admin/queues';
    next();
}, router)`

**Comment by felixmosh** [comment]
Can you make a PR for the readme, so future you will find it quickly? :]

**Comment by softbrix** [comment]
Yes, I'll try to fix that.

**Comment by aakarsh-shekhar** [comment]
Is there a way to do this when using the `@bull-board/nestjs` package? I can't seem to find a solution for it other than configuring a middleware to serve the static resources on a customized path.
