### ISSUE TITLE
Feature Request: Read-only mode

### ISSUE THREAD

**Issue by jeremysmith1** [vcapretz/bull-board#219]
I think it would be very beneficial to allow a user to configure the board to a read-only mode when configuring routes. In the UI, the buttons that affect the state could be grayed out.

My team is using bull board for observability. We would like to open up its usage to a select group of users, but we cannot allow them to modify the state of bull queues. This is why I suggest having an additional configuration object that could be passed into 'setQueues()'.

So something like the following with readonly being an optional field, defaulting to false.
```ts
setQueues( [ new BullAdapter(someQueue) ], { readonly : true } )
```

**Comment by felixmosh** [comment]
Interesting idea, it can be done ;)

PR's are welcome here

**Comment by DocX** [comment]
You can also make a simple middleware that blocks `PUT` requests and use it around the bull board app :)

Something like:
```js
const app = require('express')()
const { router } = require('bull-board')

const blockPut = (req, res, next) => {
  if (req.method == "PUT") {
    res.status(403).send("Bull board is in read-only mode")
    return
  }
  next()
}
app.use('/admin/queues', blockPut, router)
```

**Comment by jeremysmith1** [comment]
Wow, that was a quick turn around. Thanks @felixmosh

**Comment by felixmosh** [comment]
Had an hour spear during the day :]
