### ISSUE TITLE
Bull board is not opening on other environments

### ISSUE THREAD

**Issue by edilson** [vcapretz/bull-board#224]
I can open and see all the queues at the dev environment but when I'm trying to open it in a staging environment it does not load the app queues. Looking at the browser console I could see that it is trying to access the following route ```/admin/undefined/queues/?``` but it should be accessing this one ```/admin/queues/queues/?```. What could possibly be the problem for not being able to see the jobs in another env? I thought it was the helmet middleware but I disabled it and still doesn't work.

**Comment by felixmosh** [comment]
Looks like you are passing [custom render route](https://github.com/vcapretz/bull-board#hosting-router-on-a-sub-path).

Can you check what is the value inside your HTML of the `<base href="value-here" />` tag?

**Comment by edilson** [comment]
@felixmosh I couldn't find the tag you asked for. I believe it's because I'm still using the 0.9.0 version. But still I don't see why switching from environments makes it not work correctly.

**Comment by felixmosh** [comment]
Ha, do you have any errors in the console / network panel?
In versions < 1.0.0 there was an issue with helmet as well

**Comment by edilson** [comment]
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found).
```

Because it is trying to get the route I described in the issue. I don't understand because I disabled helmet and still wasn't working.

**Comment by felixmosh** [comment]
Can you share your mounting point (in `express`) of bull-board?

**Comment by edilson** [comment]
```
BullBoard.setQueues(Queue.queues.map(queue => queue.bull));
app.use('/admin/queues', BullBoard.UI);
```

**Comment by felixmosh** [comment]
This looks OK

Can you share an online example, I will able to debug it.

**Comment by edilson** [comment]
@felixmosh thanks for your help. I updated to version 0.10.0 and it worked.
