### ISSUE TITLE
fastify  how to use?

### ISSUE THREAD

**Issue by cheaprYang** [vcapretz/bull-board#225]

**Comment by felixmosh** [comment]
Maybe this plugin can help you, https://github.com/fastify/fastify-express

**Comment by josmas** [comment]
You can set it up with fastify-express as @felixmosh mentioned. For instance to server at `/queues` you can:

```
    fastify.register(require('fastify-express'))
      .after(() => {fastify.use('/queues', router)})
    await fastify.listen(__PORT__)
```

**Comment by felixmosh** [comment]
Since `v3.0.0` bull-board supports fastify natively, check the [`with-fastify`](https://github.com/felixmosh/bull-board/tree/master/examples/with-fastify) example
