### ISSUE TITLE
Add a Button to clear failed jobs

### ISSUE THREAD

**Issue by edy** [vcapretz/bull-board#24]
There are alredy two retry buttons. It would be nice to have some buttons to clean up all failed jobs and single jobs.

**Comment by vcapretz** [comment]
hey @edy thank's for the issue! 

we already added a clean option for the delayed queue to start trying it out, I think it can be added to the failed one as well.
My only concern here would be how the UI would look like with a lot of buttons per job, so I might try it out and open a PR!

(feel free to also send PR's here if you feel like it 👍)

**Comment by vcapretz** [comment]
fixed in #39
