### ISSUE TITLE
Help setting up first time

### ISSUE THREAD

**Issue by kokarn** [vcapretz/bull-board#26]
Hello!

Love the screenshot look and tried setting this up for a redis hosted on Heroku.

It's very hard because there are no error messages anywhere and the documentation seems incomplete.

How do I know if my credentials are correct?
How do I specify queues?
When it "fails" it just ends up pending forever and then fails with MaxRetries, is that intended?

After reading around this is what I ended up with
```js
const { createQueues, UI } = require('bull-board');
const app = require('express')();

const redisConfig = {
  redis: {
    port: process.env.REDIS_PORT,
    host: process.env.REDIS_HOST,
    password: process.env.REDIS_PASSWORD,
  },
}

const queues = createQueues(redisConfig);

queues.add('posts');

app.use('/admin/queues', UI)

app.listen( 3000, () => {
    console.log( `Server up and running on port 3000` );
});
```

I'd gladly help with PRs but right now I don't even know where to start 💃

**Comment by vcapretz** [comment]
hey @kokarn thank's for the feedback regarding the screenshot and for being willing to try out the lib 😄 

> How do I know if my credentials are correct?
A successful connection would return the data you have in your redis instance such as all the queues, their jobs and some information about memory usage 

> How do I specify queues?  
By doing: 
```js
queues.add('posts');
```
you successfully create a queue, but if you don' t return the instance for the created queue you won't be able to add jobs or add specify how the queue works. 
So your code should look like: 

```js
const queues = createQueues(redisConfig);
const postQueue = queues.add('posts');

postQueue.process(async job => {
    // job being processed here
  })

postQueue.add({ testEvent: true }) // adds a job in the queue with the specified object
```

I ran some tests locally and if you have wrong credentials, Bull board will eventually throw with a timeout exception, the infinite loading state in the UI is definitely not the best way to handle it 😅 

I do agree that bull-board's documentation can be improved! But keep in mind that when you're handling the queues itself and how their API works, accepted params etc you're dealing with Bull, so some of you doubts can be answered by reading their docs: https://github.com/OptimalBits/bull#quick-guide 

let me know if you still encounter any problems!

**Comment by kokarn** [comment]
I actually managed to get it working, so will probably submit some docs updates for what I needed :)

The `queues.add` part was not in the docs for just using the UI as one example.

Agreed that the silent throw was not the most optimal way.
Just try to very early make sure that you have all the credentials needed and maybe that you can connect?

**Comment by vcapretz** [comment]
yep! also maybe catching the creation of queues and provide an error state in the UI about what went wrong! 

feel free to send the PR's! thanks for that ❤️

**Comment by kokarn** [comment]
Looking great! Thanks for fixing this, sorry I never got around to it.

**Comment by vcapretz** [comment]
Let us know if there are more things we can improve! We are now introducing a proper webpage with docs so we can expand it even more 😁
