### ISSUE TITLE
Dead dependency, three high security risks

### ISSUE THREAD

**Issue by tsujp** [vcapretz/bull-board#27]
bull-board currently uses `vorpal` as a dependency, which was last updated in August of 2018.

There are three high-risk security vulnerabilities in a dependency of vorpal relating to lodash which were fixed in 2017, see them using `npm audit`

Path for all, `bull-repl > vorpal > inquirer > lodash`

* https://npmjs.com/advisories/577
* https://npmjs.com/advisories/782
* https://npmjs.com/advisories/1065

It seems to me the alternatives are to use instead either:

1. https://github.com/tj/commander.js
2. https://github.com/oclif/oclif
3. https://github.com/yargs/yargs
2. https://github.com/vorpaljs-reforged/vorpal

I am not familiar with Vorpal or Oclif which would we prefer? This security issue really must be addressed and since the only way to do it is to change dependencies, as the one it's in is dead, there needs to be some discussed about what CLI bull-board is going to in-future use.

**Comment by vcapretz** [comment]
hey @tsujp thank you for opening this issue! 

bull-board currently does not use `vorpal` nor provides a CLI for using Bull, we provide a UI for that instead

maybe you've opened this issue in the wrong repo?
it seems you're referring to https://github.com/darky/bull-repl instead! 

if that was not what you meant please let me know 😄

**Comment by tsujp** [comment]
OH MY. This is embarrassing.. sorry about that :(

Kinda of funny though.. I even pasted from the terminal and forgot to double check the name yikes.
