### ISSUE TITLE
Add option to clean jobs 

### ISSUE THREAD

**Issue by vcapretz** [vcapretz/bull-board#3]
We can start with a button to clean all the jobs in the delayed status, can probably be expanded to all the statuses

**Comment by alexleroyross** [comment]
Hello!  I am a college student, and I am working with some classmates to try to contribute to an open source project within the next couple weeks.  Would it be all right if we tried to implement this?  I've forked this repo, and we are ready to work on it.

I just had a quick question.  When you say to "clean" delayed jobs, do you just mean you want them removed from the queue?  Or do you want them promoted for immediate processing?  Or do you mean something else?

Thank you in advance.
