### ISSUE TITLE
progress bar not working ?

### ISSUE THREAD

**Issue by abdolrhman** [vcapretz/bull-board#36]
Hey, thanks for this great dashboard,
i am not sure, but after a job finishes , the progress bar doesnt go to 100% it gust go to finished tab,
but the percentege progress still 0,

also this is my code :-

`myFirstQueue.add('normal', {
  name: 'Hello',
});`

`
  myFirstQueue.process('normal', (job, done) => {
    for (let i=0;i<=1000;i++){
      file.write('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
  incididunt ut labore et dolore magna aliqua.');
    }
    done();
  });
`

how could i make the process take time , so i can see the progess in the dashboard,
would appreciate any help,
and thanks for this great work

**Comment by vcapretz** [comment]
hey @abdolrhman thank's for the feedback! 

Please refer to Bull's docs: [here](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobprogress) and [here](https://optimalbits.github.io/bull/) (Consumer section) for more information on how to track progress in a job! 

Note that the progress report is for each job, not in the queue itself, the logic on how often you want to report the progress and how to do so it's up to you and may vary depending on your implementation! 

If you still have any doubts let me know 😄

**Comment by abdolrhman** [comment]
totally my bad 💯
