### ISSUE TITLE
The completed and failed counts don't seem to reflect queue status

### ISSUE THREAD

**Issue by humphd** [vcapretz/bull-board#41]
We're using Bull Board on a project, and it's been really helpful to visualize what's happening in our queue.  However, we're finding that the `completed` and `failed` counts don't seem to reflect the current status of the queue.  Our code gets all kinds of `completed` and `failed` events, which we use to drive our app.  But we see nothing in the UI:

<img width="1161" alt="Screen Shot 2019-12-04 at 3 47 55 PM" src="https://user-images.githubusercontent.com/427398/70180196-8719f500-16ad-11ea-8fd6-94a1b54e6785.png">

I do find that `failed` events in Bull don't always have the right `err`, which I've filed upstream in https://github.com/OptimalBits/bull/issues/1326.  But this looks like a Bull Board issue vs Bull.

**Comment by vcapretz** [comment]
Hey @humphd, thanks for opening the issue and for using bull-board 😄 

can you provide some information like the node, redis and bull versions you are using? it does seem odd that the completed and failed events are not being reported while they should be, I'll try to take a look as soon as I can 👍

**Comment by humphd** [comment]
- node: v12.13.1
- Bull: 3.12.1
- redis: 5.0.6 (macOS, build=7a57e483d6f8b275)

**Comment by vcapretz** [comment]
hey @humphd, a lot has changed since the time you opened the pr 😅 I'm closing this issue for now but please feel free to reopen it if the issue persists in the latest version (1.2.0 as of the time of this comment) 

thank you very much!
