### ISSUE TITLE
Bullboard is not showing

### ISSUE THREAD

**Issue by ariusxi** [vcapretz/bull-board#47]
I was trying to run bullboard with Apollo Server, but somehow is not showing anymore the dashboard, when i try to access the is returning this to me.

![Captura de tela de 2020-01-06 09-57-03](https://user-images.githubusercontent.com/15126865/71820745-d5d0fb00-306e-11ea-9a55-510c12ef7a20.png)

I was starting the bullboard with a middleware and adding the queue with this code, after i debug aparently is normally working.

![Captura de tela de 2020-01-06 10-20-52](https://user-images.githubusercontent.com/15126865/71820785-fc8f3180-306e-11ea-8035-943037262332.png)

And adding to my application with this code.

![Captura de tela de 2020-01-06 10-21-17](https://user-images.githubusercontent.com/15126865/71820803-13ce1f00-306f-11ea-8163-de5726c6bf1c.png)

Node version: v10.15.2
Bullboard version: ^0.5.0
Bull version: ^3.12.1

**Comment by ex7r3me** [comment]
Hey @ariusxi 
I've made a basic project with apollo and it seems they work fine together, maybe it has a conflict with other middleware something like this. here is the sample code:
https://github.com/ex7r3me/apollo-bullboard-sample
can you share your project or sample code, or are there any logs in the server? you can check the network tab in chrome too, maybe it's trying to fetch a wrong resource and that can be a good clue.

**Comment by ariusxi** [comment]
@ex7r3me thanks for the example, i'll try it
