### ISSUE TITLE
Extend the failed message in the ui.

### ISSUE THREAD

**Issue by GarciaSiego** [vcapretz/bull-board#68]
Currently the Bull-board is not providing the needed info. 

For example when a job fails we retry it X amount of times depending on the endpoint and this returns `‘job stalled more than allowable limit’` when it fails. Before in Kueue this would give the data object which contained the reason for failing. 

Currently it's only possible to see the complete message by calling `‘jobs/failed/retrieve/0/99999999’ `endpoint.

For this I would like the DATA and OPS object to be added to the failed job or an other solution would be to add a link to retrieve the complete message.

Solution one extend the array of queue(ui/components/Queue.js 63) :
`failed: ['id', 'failedReason','data', 'timestamps', 'progress', 'attempts', 'retry'],`

**Comment by O1lpunch3r** [comment]
Yeah, i would be nice to see job-data and job-options in failed tab.

**Comment by Juanperezc** [comment]
I think it would be very helpful

**Comment by vcapretz** [comment]
hey, I might do it!

Just want to be clear: 😅 
what is needed is that the `failed` tab also shows the `data` field right? so you get access to the job's original data

**Comment by O1lpunch3r** [comment]
> hey, I might do it!
> 
> Just want to be clear: sweat_smile
> what is needed is that the `failed` tab also shows the `data` and `opts` fields right? so you get access to the job's original data

Exactly :)

**Comment by vcapretz** [comment]
done and release in v1.0.0-alpha.6 😄
