### ISSUE TITLE
Closing of Queue isn't handled

### ISSUE THREAD

**Issue by Imbuedhush** [vcapretz/bull-board#84]
Hello
If you will try to setQueue(bullInstance) to the board and then bullInstance.close() => it will produce error "Error: Connection is closed.", please make it just removing it from dashboard

**Comment by Imbuedhush** [comment]
here is completed code for removing of queue from dashboard
Not sure i can ask a pull request
  removeQueues: (bullQueues) => {
    if (!Array.isArray(bullQueues)) {
      bullQueues = [bullQueues];
    }

    bullQueues.forEach((item) => {
      delete queues[item.name]
    })

    return queues
  }

**Comment by vcapretz** [comment]
hey @Imbuedhush 👋 

thanks for opening the issue with the code suggestion! I think this is a valid API for us to add, so if you want to please feel free to open a PR 😄 

cc @erikengervall let me know if you have any concerns regarding this

**Comment by vcapretz** [comment]
hey, @Imbuedhush 👋 

we have PR #88 now that introduces a method to replace the queues, so you would send only the ones you want to keep in the dashboard, would that suffice the needs for you? if so I'll go ahead and close this issue as soon as that PR is merged 😄 

thanks!

**Comment by Imbuedhush** [comment]
yes, it's fine
thank you
