### ISSUE TITLE
1.0.0-alpha.5 Missing Dependencies

### ISSUE THREAD

**Issue by AgentSource** [vcapretz/bull-board#85]
Testing out 1.0.0-alpha.5...

**Current package version**
- Bull => 3.13.0
- BullMQ => Not installed

**Steps Taken**

1.`npm i bull-board@1.0.0-alpha.5`
2. `tsc -p project_src`

However tsc fails and I get the error below

`node_modules/bull-board/dist/index.d.ts:2:34 - error TS2307: Cannot find module 'bullmq'.
2 import { Queue as QueueMq } from 'bullmq';`

`node_modules/bull-board/dist/index.d.ts:3:30 - error TS2307: Cannot find module 'express-serve-static-core'.`
`3 declare const router: import("express-serve-static-core").Express;`

**Note** I tested _1.0.0-alpha.4_ to confirm and got the same error

Also manually installed _bullmq_ package and error did go away however I received this new error

`node_modules/bullmq/dist/interfaces/sandboxed-job.d.ts:3:57 - error TS2304: Cannot find name 'Omit'.`

`3 export interface SandboxedJob<T = any, R = any> extends Omit<JobJson, 'data' | 'opts' | 'progress' | 'log' | 'returnValue'> {`

**Comment by vcapretz** [comment]
Thanks for reporting it! 

We have this bug now because of we need the types coming from bullmq and Bull at the same time, to be honest I’m not sure how to solve it but I will take a look ☺️

**Comment by Yurickh** [comment]
`Omit` was introduced in [typescript v3.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type).
Be sure to check if your version of typescript satisfies it.

I'd also recommend adding a section on the readme regarding which ts versions are supported, @vcapretz.

**Comment by HugoPoi** [comment]
I test the `alpha.10`, I'm not sure if it's intended that `bullmq` to be mandatory and if this is a peer dependency ?
We should put 
```
    "bull": "^3.13.0",
    "bullmq": "^1.8.2",
```
in peerDependencies I think, and have a conditional require/import on them.
