### ISSUE TITLE
Access to returned value?

### ISSUE THREAD

**Issue by george-norris-salesforce** [vcapretz/bull-board#86]
> The value returned by your process function will be stored in the jobs object and can be accessed later on, for example in a listener for the completed event

Is the object / value that is returned by the consumer available in the dashboard? I'm seeing the object that is _passed_ to the consumer, and the options — but I don't actually see the value that is returned.

**Comment by vcapretz** [comment]
Perks of not keeping the docs updated 😅

We are currently working on a 1.0 release and if you’re looking to master you’re gonna see a lot of new things we introduced, such as this one you mentioned.

The very first version of bull-board worked by essentially creating the queues for you, so it returned their values to make it possible further usage in your application.

Then we introduced a new way in which you actually create/manage the queues in your application and just let bull-board know the ones you want to monitor. (We are keeping only this one for v1.0) 

Maybe take a look at the example file in the repo to get an idea of how you can do it while I don’t properly update the docs 😃

Thank you for opening the issue

**Comment by george-norris-salesforce** [comment]
Excellent. Thank you! :)
