### ISSUE TITLE
Bull could be an external dependency instead of being provided by bull-board

### ISSUE THREAD

**Issue by vcapretz** [vcapretz/bull-board#9]
This would be a breaking change, basically removing the `createQueues` method and instead of keeping track of the queues internally, we would rather accept queues as a parameter (probably to `UI` or a config method).

Major benefit would be that users have more control on how to use Bull on their own and maybe even supporting integration with other libs

**Comment by erikengervall** [comment]
Tbh you shouldn't discard existing behaviour too easily. Consider simply extending it by giving the user the _option_ to provide queues themselves :)

**Comment by vcapretz** [comment]
probably addressed in #28
