### ISSUE TITLE
Reciveing loading screen when i try to manage my queues

### ISSUE THREAD

**Issue by gabeMoreira** [vcapretz/bull-board#92]
Hi, I'm trying to test bull-board but using the example but I'm getting a screen with:

> loading...

and not bull-board management screen:
Is the same as the example
```
const { createQueues } = require('bull-board')
 
	const redisConfig = {
  		redis: {
    		port: 6379,
    		host: "127.0.0.1"
  	},
	}
 
	const queues = createQueues(redisConfig)

	const helloQueue = queues.add('helloQueue') // adds a queue
	const helloQueueWithOpts = queues.add('helloQueue', {
  		prefix: 'hello',
	}) // adds a queue with QueueOptions https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queue
 
	// defines how the queue works
	helloQueue.process(async job => {
  		console.log(`Hello ${job.data.hello}`)
	})
 
	helloQueue.add({ hello: 'world' }) // adds a job to the queue
```
And later

```
const { UI } = require('bull-board')
 
	app.use('/admin/bullDash', UI)
```

Someone knows what is happening?

**Comment by vcapretz** [comment]
hey @gabeMoreira, thanks for giving bull-board a try 😄 

We are currently working on a v1 release that's in alpha, one of the breaking changes is that we are no longer going to support `createQueues`, so if you look at the current example.ts file you will see a newer way of doing it using `setQueues` when you already have created your queues separately using Bull.

**Comment by gabeMoreira** [comment]
> hey @gabeMoreira, thanks for giving bull-board a try 😄
> 
> We are currently working on a v1 release that's in alpha, one of the breaking changes is that we are no longer going to support `createQueues`, so if you look at the current example.ts file you will see a newer way of doing it using `setQueues` when you already have created your queues separately using Bull.

In my project I basically do this
```
import Queue from './lib/Queue'
import BullBoard from 'bull-board'
```
And to set a queue in dashbord
```
BullBoard.setQueues(Queue)
app.use('/admin/queues' BullBoard.UI)

```

But the loading screen still appears, i'm doing correctly?

**Comment by gabeMoreira** [comment]
It's working fine now, I was trying to call bull-board before my authorization middleware.
