### ISSUE TITLE
Integration with NestJS

### ISSUE THREAD

**Issue by piby180** [vcapretz/bull-board#95]
How can we integrate the UI to nestjs project where queues are alreay created and maanged by @nest/bull package?

**Comment by iam4x** [comment]
Hi @piby180 

This is how you integrate with nestjs: 

* https://github.com/iam4x/bobarr/blob/master/packages/api/src/main.ts#L11
* https://github.com/iam4x/bobarr/blob/master/packages/api/src/modules/jobs/jobs.service.ts#L32-L39

You add bull-board directly to the express app returned from nestjs and register your queues in one service where you inject all the queues you want to visualize.

**Comment by piby180** [comment]
Thanks a lot :)
