### ISSUE TITLE
Question: what's a blocked client

### ISSUE THREAD

**Issue by tkrugg** [vcapretz/bull-board#99]
Hello, I'm wondering what "Blocked client" indicates on the UI, and if there is something I should do about them. 

![image](https://user-images.githubusercontent.com/2982512/80347489-a2f48200-886c-11ea-94bb-5ecfa78c3302.png)

**Comment by rivernews** [comment]
Hi @tkrugg , I wondered the same thing a while ago. After using more redis features I think you can find out the answer in this page [Blocking commands in Redis modules](https://redis.io/topics/modules-blocking-ops). My understanding is a client will be set as blocked client once it's running a blocking command and is thereby blocked at the moment. You will find explanation about blocking command in the web page as well.

**Comment by tkrugg** [comment]
thanks @rivernews this makes sense!
